CREATE TABLE PRODUIT
(
    ID SERIAL PRIMARY KEY,
    NOM_PRODUIT TEXT,
    PRIX_PRODUIT DOUBLE PRECISION
);
INSERT INTO PRODUIT (NOM_PRODUIT, PRIX_PRODUIT) VALUES ('Pomme', 1.5);
INSERT INTO PRODUIT (NOM_PRODUIT, PRIX_PRODUIT) VALUES ('Poire', 1.2);
INSERT INTO PRODUIT (NOM_PRODUIT, PRIX_PRODUIT) VALUES ('Banane', 1.8);

CREATE TABLE CATEGORIE
( 
    ID SERIAL PRIMARY KEY,
    NOM_CATEGORIE TEXT,
);

INSERT INTO CATEGORIE (NOM_CATEGORIE) VALUES ('Fruit');
INSERT INTO CATEGORIE (NOM_CATEGORIE) VALUES ('Legume');
INSERT INTO CATEGORIE (NOM_CATEGORIE) VALUES ('Viande');

CREATE TABLE CATEGORIE_PRODUIT
(
    ID SERIAL PRIMARY KEY,
    ID_PRODUIT INT,
    ID_CATEGORIE INT,
    FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT(ID),
    FOREIGN KEY (ID_CATEGORIE) REFERENCES CATEGORIE(ID)
);
INSERT INTO CATEGORIE_PRODUIT (ID_PRODUIT, ID_CATEGORIE) VALUES (1, 1);
INSERT INTO CATEGORIE_PRODUIT (ID_PRODUIT, ID_CATEGORIE) VALUES (2, 1);